const DAY=86400000,S=new Date('2016-07-14T00:00:00Z'),E=new Date('2026-07-15T00:00:00Z');
const A=[['QQQ','QQQ',[-15,-25,-35],[.1,.2,.3],20,'stock'],['NVDA','NVDA',[-25,-35,-45,-60],[.1,.2,.3,.4],20,'stock'],['TSM','TSM',[-25,-35,-45,-60],[.1,.2,.3,.4],20,'stock'],['AVGO','AVGO',[-25,-35,-45,-60],[.1,.2,.3,.4],20,'stock'],['GOOGL','GOOGL',[-20,-30,-40],[.1,.2,.3],20,'stock'],['AMD','AMD',[-25,-35,-45,-60],[.1,.2,.3,.4],25,'stock'],['MRVL','MRVL',[-25,-35,-45,-60],[.1,.2,.3,.4],20,'stock'],['RKLB','RKLB',[-50,-65,-80],[.15,.3,.55],10,'stock'],['BTC','BTC-USD',[-25,-40,-55,-70,-85],[.1,.2,.3,.4,.5],30,'cycle'],['SPCX',null,[],[],0,'none']].map(x=>({s:x[0],y:x[1],r:x[2],f:x[3],cap:x[4],m:x[5]}));
const n=v=>Number.isFinite(Number(v))?Number(v):0,d=t=>new Date(t).toISOString().slice(0,10),mo=t=>d(t).slice(0,7);
async function yf(s){const p1=S.getTime()/1000|0,p2=E.getTime()/1000|0,u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?period1=${p1}&period2=${p2}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`,r=await fetch(u,{cache:'no-store',headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${s}:${r.status}`);const z=(await r.json())?.chart?.result?.[0];if(!z)throw Error(`${s}:empty`);const ts=z.timestamp||[],q=z.indicators?.quote?.[0]||{},a=z.indicators?.adjclose?.[0]?.adjclose||[],o=[];for(let i=0;i<ts.length;i++){const rc=n(q.close?.[i]),ac=n(a[i]??rc);if(!(rc>0&&ac>0))continue;const f=ac/rc;o.push({ts:ts[i]*1000,c:ac,h:(n(q.high?.[i])*f)||ac})}return o.filter(x=>x.ts>=S&&x.ts<E)}
function prep(rows,a){let official=0,ath=0;return rows.map(x=>{let reset=false,ref=0;if(a.m==='cycle'){if(x.h>ath){ath=x.h;reset=true}ref=ath}else{if(!official||x.h>official){official=x.h;reset=true}ref=official}return {...x,reset,dd:ref?100*(x.c/ref-1):0}})}
function mdates(rows){const m=new Map();for(const x of rows){if(new Date(x.ts).getUTCDate()<14)continue;const k=mo(x.ts);if(!m.has(k))m.set(k,x.ts)}return m}
function stats(nav,rf){let peak=-1,mdd=0,pd=null,td=null,re=[],ex=[],dn=[];for(let i=0;i<nav.length;i++){const x=nav[i];if(x.i>peak){peak=x.i;pd=x.date}const dd=x.i/peak-1;if(dd<mdd){mdd=dd;td=x.date}if(i){const r=x.i/nav[i-1].i-1,fr=(rf.get(x.date)||0)/100/365;re.push(r);ex.push(r-fr);if(r-fr<0)dn.push((r-fr)**2)}}const avg=a=>a.reduce((s,x)=>s+x,0)/(a.length||1),sd=a=>Math.sqrt(avg(a.map(x=>(x-avg(a))**2))),vol=sd(re)*Math.sqrt(365),sh=sd(ex)?avg(ex)*365/(sd(ex)*Math.sqrt(365)):0,so=dn.length?avg(ex)*365/(Math.sqrt(avg(dn))*Math.sqrt(365)):0;const y=nav.filter(x=>x.date>='2022-01-01'&&x.date<='2022-12-31');let yp=-1,ym=0;for(const x of y){yp=Math.max(yp,x.i);ym=Math.min(ym,x.i/yp-1)}return {volatility:vol,sharpe:sh,sortino:so,maxDrawdown:mdd,mddPeakDate:pd,mddTroughDate:td,drawdown2022:ym}}
function run(series,rf,ratio){const st=new Map(),pm=new Map(),mm=new Map(),last=new Map();for(const a of A){const rows=a.y?(series.get(a.s)||[]):[],p=a.y?prep(rows,a):[];pm.set(a.s,new Map(p.map(x=>[x.ts,x])));mm.set(a.s,a.y?mdates(rows):new Map());st.set(a.s,{cash:0,sh:0,con:0,inv:0,int:0,done:new Set(),buys:0})}const cal=[...new Set([...series.values()].flat().map(x=>x.ts))].sort((a,b)=>a-b),nav=[];let rate=0,prev=0,idx=1;for(const ts of cal){const date=d(ts);if(rf.has(date))rate=rf.get(date);let add=0;for(const a of A){const s=st.get(a.s),interest=s.cash*(rate/100)/365;s.cash+=interest;s.int+=interest;const row=pm.get(a.s).get(ts);if(row)last.set(a.s,row.c);const k=mo(ts);if(a.y&&mm.get(a.s).get(k)===ts){s.cash+=10;s.con+=10;add+=10;const dca=10*ratio;if(dca>0){s.cash-=dca;s.sh+=dca/row.c;s.inv+=dca}}if(a.y&&ratio<1&&row&&a.r.length){if(row.reset)s.done=new Set();for(let i=0;i<a.r.length;i++)if(!s.done.has(i)&&row.dd<=a.r[i]){const amt=Math.min(s.cash*a.f[i],a.cap,s.cash);if(amt>=1){s.cash-=amt;s.sh+=amt/row.c;s.inv+=amt;s.done.add(i);s.buys++}}}}let value=0;for(const a of A){const s=st.get(a.s);value+=s.cash+s.sh*n(last.get(a.s))}if(prev>0)idx*=Math.max(.000001,(value-add)/prev);prev=value;nav.push({ts,date,i:idx})}
const ml=[];for(let x=new Date(Date.UTC(S.getUTCFullYear(),S.getUTCMonth(),1));x<E;x.setUTCMonth(x.getUTCMonth()+1))ml.push(mo(x));for(const a of A){const s=st.get(a.s),have=new Set([...pm.get(a.s).values()].map(x=>mo(x.ts)));for(const m of ml)if(!have.has(m)){s.cash+=10;s.con+=10}}
const assets=A.map(a=>{const s=st.get(a.s),mv=s.sh*n(last.get(a.s));return {symbol:a.s,invested:s.inv,cash:s.cash,interest:s.int,totalValue:s.cash+mv,dipBuys:s.buys}}),sum=k=>assets.reduce((z,x)=>z+n(x[k]),0),con=12100,total=sum('totalValue');return {summary:{dcaRatio:ratio,contributed:con,invested:sum('invested'),capitalUtilization:sum('invested')/con,cash:sum('cash'),interest:sum('interest'),totalValue:total,pnl:total-con,returnPct:(total-con)/con,...stats(nav,rf)},assets}}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');try{const [pairs,irx]=await Promise.all([Promise.all(A.filter(a=>a.y).map(async a=>[a.s,await yf(a.y)])),yf('^IRX')]),series=new Map(pairs),rf=new Map(irx.map(x=>[d(x.ts),Math.max(0,x.c)]));const ratios=[.5,.6,.7,.8,.9,1],results={};for(const r of ratios)results[`${Math.round(r*100)}_${Math.round((1-r)*100)}`]=run(series,rf,r);res.status(200).json({ok:true,version:'v5-dca-ratio-sweep',methodology:{budget:'100U/month, ten 10U sleeves',scope:'exploratory uniform DCA ratio across nine tradable sleeves; SPCX remains cash',cycle:'B official high breakout',cashYield:'^IRX 13-week T-bill',ratios},results,generatedAt:new Date().toISOString()})}catch(e){res.status(500).json({ok:false,error:e.message})}}
