const DAY=86400000,START=new Date('2016-07-14T00:00:00Z'),END=new Date('2026-07-15T00:00:00Z');
const ASSETS=[
['QQQ','QQQ',[-15,-25,-35],10,0,'stock',[.1,.2,.3],20],['NVDA','NVDA',[-25,-35,-45,-60],5,5,'stock',[.1,.2,.3,.4],20],['TSM','TSM',[-25,-35,-45,-60],5,5,'stock',[.1,.2,.3,.4],20],['AVGO','AVGO',[-25,-35,-45,-60],5,5,'stock',[.1,.2,.3,.4],20],['GOOGL','GOOGL',[-20,-30,-40],5,5,'stock',[.1,.2,.3],20],['AMD','AMD',[-25,-35,-45,-60],0,10,'stock',[.1,.2,.3,.4],25],['MRVL','MRVL',[-25,-35,-45,-60],0,10,'stock',[.1,.2,.3,.4],20],['RKLB','RKLB',[-50,-65,-80],0,10,'stock',[.15,.3,.55],10],['BTC','BTC-USD',[-25,-40,-55,-70,-85],5,5,'cycle',[.1,.2,.3,.4,.5],30],['SPCX',null,[-20,-35,-50,-65],0,10,'none',[.1,.2,.3,.4],10]
].map(x=>({symbol:x[0],yahoo:x[1],rules:x[2],dca:x[3],dip:x[4],mode:x[5],fractions:x[6],cap:x[7]}));
const num=v=>Number.isFinite(Number(v))?Number(v):0,ds=t=>new Date(t).toISOString().slice(0,10),mk=t=>ds(t).slice(0,7);
async function yahoo(s){const p1=START.getTime()/1000|0,p2=END.getTime()/1000|0,u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?period1=${p1}&period2=${p2}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`,r=await fetch(u,{cache:'no-store',headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${s}:${r.status}`);const j=await r.json(),z=j?.chart?.result?.[0];if(!z)throw Error(`${s}:empty`);const ts=z.timestamp||[],q=z.indicators?.quote?.[0]||{},a=z.indicators?.adjclose?.[0]?.adjclose||[],out=[];for(let i=0;i<ts.length;i++){const rc=num(q.close?.[i]),ac=num(a[i]??rc);if(!(rc>0&&ac>0))continue;const f=ac/rc,ah=num(q.high?.[i])*f;out.push({ts:ts[i]*1000,close:ac,high:ah>0?ah:ac})}return out.filter(r=>r.ts>=START&&r.ts<END)}
function monthDates(rows){const m=new Map();for(const r of rows){if(new Date(r.ts).getUTCDate()<14)continue;const k=mk(r.ts);if(!m.has(k))m.set(k,r.ts)}return m}
function prepared(rows,asset,variant){let ath=0,official=0,rollingPrev=0,w=[],confirm=0,resets=0;return rows.map(r=>{let ref=0,reset=false;if(asset.mode==='cycle'){if(r.high>ath+1e-9){ath=r.high;reset=true;resets++}ref=ath}else if(variant==='A'){w.push(r);while(w.length&&w[0].ts<r.ts-365*DAY)w.shift();ref=w.reduce((m,x)=>Math.max(m,x.high),0);if(ref>rollingPrev+1e-9){reset=true;resets++}rollingPrev=ref}else{if(!official){official=r.high;reset=true;resets++}if(variant==='B'&&r.high>official+1e-9){official=r.high;reset=true;resets++}if(variant==='C'){if(r.close>official*1.02)confirm++;else confirm=0;if(confirm>=5){official=Math.max(official,r.high);reset=true;resets++;confirm=0}}ref=official=Math.max(official,variant==='B'?r.high:official)}return {...r,dd:ref>0?(r.close/ref-1)*100:0,reset,resets}})}
function risk(nav,rf){const rets=[],excess=[],down=[];let peak=-Infinity,peakDate=null,mdd=0,mddPeak=null,mddTrough=null;for(let i=0;i<nav.length;i++){const x=nav[i];if(x.index>peak){peak=x.index;peakDate=x.date}const dd=x.index/peak-1;if(dd<mdd){mdd=dd;mddPeak=peakDate;mddTrough=x.date}if(i){const r=x.index/nav[i-1].index-1,fr=(rf.get(x.date)||0)/100/365;rets.push(r);excess.push(r-fr);if(r-fr<0)down.push((r-fr)**2)}}const mean=a=>a.reduce((s,x)=>s+x,0)/(a.length||1),sd=a=>Math.sqrt(mean(a.map(x=>(x-mean(a))**2)));const annRet=Math.pow(nav.at(-1).index/nav[0].index,365/((nav.at(-1).ts-nav[0].ts)/DAY))-1,vol=sd(rets)*Math.sqrt(365),sharpe=sd(excess)>0?mean(excess)*365/(sd(excess)*Math.sqrt(365)):0,downDev=Math.sqrt(mean(down))*Math.sqrt(365),sortino=downDev>0?mean(excess)*365/downDev:0;const y=nav.filter(x=>x.date>='2022-01-01'&&x.date<='2022-12-31');let yp=-Infinity,ym=0,ypd=null,ytd=null;for(const x of y){if(x.index>yp){yp=x.index;ypd=x.date}const d=x.index/yp-1;if(d<ym){ym=d;ytd=x.date}}return {twrAnnualized:annRet,annualizedVolatility:vol,sharpe,sortino,maxDrawdown:mdd,mddPeakDate:mddPeak,mddTroughDate:mddTrough,drawdown2022:ym,drawdown2022PeakDate:ypd,drawdown2022TroughDate:ytd}}
function simulate(series,rf,variant){const st=new Map(),prep=new Map(),months=new Map(),maps=new Map(),last=new Map();for(const a of ASSETS){const rows=a.yahoo?(series.get(a.symbol)||[]):[];const p=a.yahoo?prepared(rows,a,variant):[];prep.set(a.symbol,p);months.set(a.symbol,a.yahoo?monthDates(rows):new Map());maps.set(a.symbol,new Map(p.map(r=>[r.ts,r])));st.set(a.symbol,{cash:0,shares:0,contributed:0,invested:0,interest:0,dcaBuys:0,dipBuys:0,done:new Set(),tiers:Array(a.rules.length).fill(0),resets:0})}
const cal=[...new Set([...series.values()].flat().map(r=>r.ts))].sort((a,b)=>a-b),nav=[];let prev=0,index=1,lastRate=0;for(const ts of cal){const date=ds(ts);if(rf.has(date))lastRate=rf.get(date);let contribution=0;for(const a of ASSETS){const s=st.get(a.symbol);s.cash+=s.cash*(lastRate/100)/365;s.interest+=s.cash*(lastRate/100)/365;const row=maps.get(a.symbol).get(ts);if(row)last.set(a.symbol,row.close);const k=mk(ts);if(months.get(a.symbol).get(k)===ts){s.cash+=10;s.contributed+=10;contribution+=10;if(variant==='DCA'){s.cash-=10;s.shares+=10/row.close;s.invested+=10;s.dcaBuys++}else if(a.dca>0){s.cash-=a.dca;s.shares+=a.dca/row.close;s.invested+=a.dca;s.dcaBuys++}}if(variant!=='DCA'&&row&&a.dip>0){if(row.reset){s.done=new Set();s.resets++}for(let i=0;i<a.rules.length;i++)if(!s.done.has(i)&&row.dd<=a.rules[i]){const amt=Math.min(s.cash*a.fractions[i],a.cap,s.cash);if(amt>=1){s.cash-=amt;s.shares+=amt/row.close;s.invested+=amt;s.dipBuys++;s.tiers[i]++;s.done.add(i)}}}}
let value=0;for(const a of ASSETS){const s=st.get(a.symbol);value+=s.cash+s.shares*num(last.get(a.symbol))}if(prev>0)index*=Math.max(.000001,(value-contribution)/prev);prev=value;nav.push({ts,date,index,value})}
const monthList=[];for(let d=new Date(Date.UTC(START.getUTCFullYear(),START.getUTCMonth(),1));d<END;d.setUTCMonth(d.getUTCMonth()+1))monthList.push(mk(d));for(const a of ASSETS){const s=st.get(a.symbol),have=new Set((prep.get(a.symbol)||[]).map(r=>mk(r.ts)));for(const m of monthList)if(!have.has(m)){s.cash+=10;s.contributed+=10}}
const assets=ASSETS.map(a=>{const s=st.get(a.symbol),mv=s.shares*num(last.get(a.symbol));return {symbol:a.symbol,contributed:s.contributed,invested:s.invested,cash:s.cash,interest:s.interest,totalValue:s.cash+mv,dipBuys:s.dipBuys,tierTriggers:s.tiers,resets:s.resets}}),sum=k=>assets.reduce((z,x)=>z+num(x[k]),0),contributed=sum('contributed'),totalValue=sum('totalValue');return {summary:{contributed,invested:sum('invested'),cash:sum('cash'),interest:sum('interest'),totalValue,pnl:totalValue-contributed,returnPct:(totalValue-contributed)/contributed,capitalUtilization:sum('invested')/contributed,...risk(nav,rf)},assets}}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');try{const [pairs,irx]=await Promise.all([Promise.all(ASSETS.filter(a=>a.yahoo).map(async a=>[a.symbol,await yahoo(a.yahoo)])),yahoo('^IRX')]),series=new Map(pairs),rf=new Map(irx.map(r=>[ds(r.ts),Math.max(0,r.close)]));const out={DCA:simulate(series,rf,'DCA'),A:simulate(series,rf,'A'),B:simulate(series,rf,'B'),C:simulate(series,rf,'C')};res.status(200).json({ok:true,version:'v4-cycle-sensitivity',definitions:{A:'rolling 365-day high increase resets',B:'new official all-time cycle high resets',C:'close > official high by 2% for 5 consecutive trading days resets'},results:out,generatedAt:new Date().toISOString()})}catch(e){res.status(500).json({ok:false,error:e.message})}}
