const DAY=86400000;const START=new Date('2016-07-14T00:00:00Z');const END=new Date('2026-07-15T00:00:00Z');
const ASSETS=[
{symbol:'QQQ',yahoo:'QQQ',rules:[-15,-25,-35],dca:10,dip:0,mode:'stock',fractions:[.1,.2,.3],cap:20},
{symbol:'NVDA',yahoo:'NVDA',rules:[-25,-35,-45,-60],dca:5,dip:5,mode:'stock',fractions:[.1,.2,.3,.4],cap:20},
{symbol:'TSM',yahoo:'TSM',rules:[-25,-35,-45,-60],dca:5,dip:5,mode:'stock',fractions:[.1,.2,.3,.4],cap:20},
{symbol:'AVGO',yahoo:'AVGO',rules:[-25,-35,-45,-60],dca:5,dip:5,mode:'stock',fractions:[.1,.2,.3,.4],cap:20},
{symbol:'GOOGL',yahoo:'GOOGL',rules:[-20,-30,-40],dca:5,dip:5,mode:'stock',fractions:[.1,.2,.3],cap:20},
{symbol:'AMD',yahoo:'AMD',rules:[-25,-35,-45,-60],dca:0,dip:10,mode:'stock',fractions:[.1,.2,.3,.4],cap:25},
{symbol:'MRVL',yahoo:'MRVL',rules:[-25,-35,-45,-60],dca:0,dip:10,mode:'stock',fractions:[.1,.2,.3,.4],cap:20},
{symbol:'RKLB',yahoo:'RKLB',rules:[-50,-65,-80],dca:0,dip:10,mode:'stock',fractions:[.15,.3,.55],cap:10},
{symbol:'BTC',yahoo:'BTC-USD',rules:[-25,-40,-55,-70,-85],dca:5,dip:5,mode:'cycle',fractions:[.1,.2,.3,.4,.5],cap:30},
{symbol:'SPCX',yahoo:null,rules:[-20,-35,-50,-65],dca:0,dip:10,mode:'unavailable',fractions:[.1,.2,.3,.4],cap:10}
];
const n=v=>Number.isFinite(Number(v))?Number(v):0;const key=t=>new Date(t).toISOString().slice(0,10);const mkey=t=>key(t).slice(0,7);
async function yahoo(s){const p1=START.getTime()/1000|0,p2=END.getTime()/1000|0;const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?period1=${p1}&period2=${p2}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`;const r=await fetch(u,{cache:'no-store',headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(`${s}:${r.status}`);const j=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error(`${s}:empty`);const ts=x.timestamp||[],q=x.indicators?.quote?.[0]||{},a=x.indicators?.adjclose?.[0]?.adjclose||[],out=[];for(let i=0;i<ts.length;i++){const rc=n(q.close?.[i]),ac=n(a[i]??rc);if(!(rc>0&&ac>0))continue;const f=ac/rc,ah=n(q.high?.[i])*f;out.push({ts:ts[i]*1000,close:ac,high:ah>0?ah:ac});}return out.filter(x=>x.ts>=START&&x.ts<END)}
async function rates(){const rows=await yahoo('^IRX');const map=new Map();for(const r of rows)map.set(key(r.ts),Math.max(0,r.close));return map}
function monthlyDates(rows){const m=new Map();for(const r of rows){const d=new Date(r.ts);if(d.getUTCDate()<14)continue;const k=mkey(r.ts);if(!m.has(k))m.set(k,r.ts)}return m}
function refs(rows,mode){let ath=0,prev=0,w=[];return rows.map(r=>{let ref=0,reset=false;if(mode==='cycle'){if(r.high>ath+1e-9){ath=r.high;reset=true}ref=ath}else{w.push({ts:r.ts,high:r.high});while(w.length&&w[0].ts<r.ts-365*DAY)w.shift();ref=w.reduce((m,x)=>Math.max(m,x.high),0);if(ref>prev+1e-9)reset=true;prev=ref}return {...r,dd:ref>0?(r.close/ref-1)*100:0,reset}})}
function buildCalendar(series){const set=new Set();for(const rows of series.values())for(const r of rows)set.add(r.ts);return [...set].sort((a,b)=>a-b)}
function metrics(nav){let peak=1,mdd=0,ret=[];for(let i=0;i<nav.length;i++){peak=Math.max(peak,nav[i].index);mdd=Math.min(mdd,nav[i].index/peak-1);if(i>0)ret.push(nav[i].index/nav[i-1].index-1)}const mean=ret.reduce((a,b)=>a+b,0)/(ret.length||1);const vol=Math.sqrt(ret.reduce((a,b)=>a+(b-mean)**2,0)/(ret.length||1))*Math.sqrt(365);return {maxDrawdown:mdd,annualizedVolatility:vol,worstDailyReturn:Math.min(0,...ret)}}
function simulate(series,rateMap,kind){const states=new Map(),prepared=new Map(),monthly=new Map(),lastPrice=new Map();for(const a of ASSETS){const rows=a.yahoo?(series.get(a.symbol)||[]):[];prepared.set(a.symbol,a.yahoo?refs(rows,a.mode):[]);monthly.set(a.symbol,a.yahoo?monthlyDates(rows):new Map());states.set(a.symbol,{cash:0,shares:0,contributed:0,invested:0,interest:0,dipBuys:0,dcaBuys:0,done:new Set()})}
const calendar=buildCalendar(series),rowMaps=new Map();for(const a of ASSETS)rowMaps.set(a.symbol,new Map((prepared.get(a.symbol)||[]).map(r=>[r.ts,r])));let prevValue=0,index=1,nav=[];let lastRate=0;for(const ts of calendar){const date=key(ts);if(rateMap.has(date))lastRate=rateMap.get(date);let contribution=0;for(const a of ASSETS){const s=states.get(a.symbol);const interest=s.cash*(lastRate/100)/365;s.cash+=interest;s.interest+=interest;const row=rowMaps.get(a.symbol).get(ts);if(row)lastPrice.set(a.symbol,row.close);const mk=mkey(ts);if(a.yahoo&&monthly.get(a.symbol).get(mk)===ts){s.cash+=10;s.contributed+=10;contribution+=10;if(kind==='dca'){s.cash-=10;s.shares+=10/row.close;s.invested+=10;s.dcaBuys++}else if(a.dca>0){s.cash-=a.dca;s.shares+=a.dca/row.close;s.invested+=a.dca;s.dcaBuys++}}if(kind==='new'&&row&&a.dip>0){if(row.reset)s.done=new Set();for(let i=0;i<a.rules.length;i++)if(!s.done.has(i)&&row.dd<=a.rules[i]){const amt=Math.min(s.cash*a.fractions[i],a.cap,s.cash);if(amt>=1){s.cash-=amt;s.shares+=amt/row.close;s.invested+=amt;s.dipBuys++;s.done.add(i)}}}}
let value=0;for(const a of ASSETS){const s=states.get(a.symbol);value+=s.cash+s.shares*n(lastPrice.get(a.symbol))}if(prevValue>0)index*=Math.max(.000001,(value-contribution)/prevValue);prevValue=value;nav.push({ts,index,value})}
const months=[];let d=new Date(Date.UTC(START.getUTCFullYear(),START.getUTCMonth(),1));while(d<END){months.push(mkey(d));d.setUTCMonth(d.getUTCMonth()+1)}for(const a of ASSETS){const s=states.get(a.symbol),have=new Set((prepared.get(a.symbol)||[]).map(r=>mkey(r.ts)));for(const m of months)if(!have.has(m)){s.cash+=10;s.contributed+=10}}
const assets=ASSETS.map(a=>{const s=states.get(a.symbol),price=n(lastPrice.get(a.symbol)),market=s.shares*price,total=s.cash+market;return {symbol:a.symbol,contributed:s.contributed,invested:s.invested,cash:s.cash,interest:s.interest,marketValue:market,totalValue:total,pnl:total-s.contributed,dcaBuys:s.dcaBuys,dipBuys:s.dipBuys}});const sum=k=>assets.reduce((x,y)=>x+n(y[k]),0),contributed=sum('contributed'),totalValue=sum('totalValue');return {summary:{contributed,invested:sum('invested'),cash:sum('cash'),interest:sum('interest'),marketValue:sum('marketValue'),totalValue,pnl:totalValue-contributed,returnPct:(totalValue-contributed)/contributed,...metrics(nav)},assets}}
module.exports=async function(req,res){res.setHeader('Cache-Control','no-store');try{const [pairs,rateMap]=await Promise.all([Promise.all(ASSETS.filter(a=>a.yahoo).map(async a=>[a.symbol,await yahoo(a.yahoo)])),rates()]);const series=new Map(pairs),dca=simulate(series,rateMap,'dca'),next=simulate(series,rateMap,'new');res.status(200).json({ok:true,version:'10y-backtest-v3-proportional-tbill-risk',methodology:{period:['2016-07-14','2026-07-14'],monthlyBudget:100,pool:'各資產獨立池',cashYield:'Yahoo Finance ^IRX 13-week Treasury bill yield, carried forward on missing days',sizing:'各層按當時該資產現金池比例買入，並設單筆上限',fractions:{core:'10/20/30/40%',RKLB:'15/30/55%',BTC:'10/20/30/40/50%'},caps:{NVDA:20,TSM:20,AVGO:20,GOOGL:20,AMD:25,MRVL:20,RKLB:10,BTC:30},risk:'以排除當日新增投入後的時間加權NAV計算MDD與波動率',caveat:'測試用途；存在存活者偏差；SPCX無公開十年價格'},pureDca:dca,newStrategy:next,difference:{totalValue:next.summary.totalValue-dca.summary.totalValue,pnl:next.summary.pnl-dca.summary.pnl,maxDrawdown:next.summary.maxDrawdown-dca.summary.maxDrawdown},generatedAt:new Date().toISOString()})}catch(e){res.status(500).json({ok:false,error:e.message})}}
