import { useEffect, useMemo, useState } from "react";

const tone = {
  green: { color: "#bbf7d0", bg: "rgba(20,83,45,.22)", border: "rgba(34,197,94,.34)" },
  yellow: { color: "#fde68a", bg: "rgba(120,53,15,.20)", border: "rgba(245,158,11,.34)" },
  red: { color: "#fecaca", bg: "rgba(127,29,29,.20)", border: "rgba(248,113,113,.34)" },
  gray: { color: "#cbd5e1", bg: "rgba(71,85,105,.20)", border: "rgba(148,163,184,.30)" },
};
function T({ v }) { const t = tone[v] || tone.gray; return t; }
function Badge({ children, toneName = "gray" }) { const t = T({ v: toneName }); return <span style={{ display: "inline-flex", alignItems: "center", padding: "4px 8px", borderRadius: 999, background: t.bg, border: `1px solid ${t.border}`, color: t.color, fontSize: 12, fontWeight: 900 }}>{children}</span>; }
function Pill({ children }) { return <span style={{ display: "inline-flex", padding: "3px 7px", borderRadius: 999, color: "#a5f3fc", background: "rgba(49,231,255,.08)", border: "1px solid rgba(49,231,255,.22)", fontSize: 11, fontWeight: 850 }}>{children}</span>; }
function Score({ label, value }) { return <div style={{ padding: 10, borderRadius: 14, background: "rgba(2,6,23,.45)", border: "1px solid rgba(49,231,255,.12)" }}><div style={{ color: "#7dd3fc", fontSize: 11, fontWeight: 900 }}>{label}</div><strong style={{ display: "block", marginTop: 4, color: "#f8fafc", fontSize: 18 }}>{value ?? "—"}</strong></div>; }
function CheckList({ title, items = [] }) { if (!items.length) return null; return <div style={{ marginTop: 12 }}><h4 style={{ margin: "0 0 8px", color: "#e0fbff", fontSize: 14 }}>{title}</h4><div style={{ display: "grid", gap: 7 }}>{items.map((x) => <div key={x.name} style={{ padding: 9, borderRadius: 12, background: "rgba(15,23,42,.52)", border: "1px solid rgba(148,163,184,.13)" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><strong style={{ color: "#f8fafc", fontSize: 12 }}>{x.name}</strong><span style={{ color: x.status === "通過" ? "#bbf7d0" : x.status === "失敗" ? "#fecaca" : "#fde68a", fontSize: 12, fontWeight: 900 }}>{x.status}{x.score !== null && x.score !== undefined ? `｜${x.score}` : ""}</span></div><div style={{ marginTop: 4, color: "#94a3b8", fontSize: 12, lineHeight: 1.45 }}>{x.reason}</div></div>)}</div></div>; }
function AuditCard({ audit }) { const qTone = audit.tone || "gray"; return <article style={{ padding: 14, borderRadius: 22, background: "linear-gradient(135deg, rgba(11,19,36,.88), rgba(5,11,24,.80))", border: "1px solid rgba(49,231,255,.18)", boxShadow: "0 18px 38px rgba(0,0,0,.30)" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10, alignItems: "flex-start" }}><div><h3 style={{ margin: 0, fontSize: 24, color: "#f8fafc" }}>{audit.symbol}</h3><div style={{ marginTop: 3, color: "#94a3b8", fontWeight: 850 }}>{audit.underlying}｜{audit.role}</div></div><Badge toneName={qTone}>{audit.qualityLabel}</Badge></div><div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginTop: 10 }}><Pill>{audit.pipeline}</Pill><Pill>{audit.sourceStatus}</Pill><Pill>{audit.scoringModel}</Pill></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0,1fr))", gap: 8, marginTop: 12 }}><Score label="客觀" value={audit.objectiveScore} /><Score label="質化" value={audit.qualitativeScore} /><Score label="總分" value={audit.totalScore} /></div>{audit.risk ? <div style={{ marginTop: 12, padding: 10, borderRadius: 14, color: "#fde68a", background: "rgba(120,53,15,.18)", border: "1px solid rgba(245,158,11,.26)", fontWeight: 850, fontSize: 12, lineHeight: 1.45 }}>主要風險：{audit.risk}</div> : null}{audit.majorFails?.length ? <div style={{ marginTop: 10, padding: 10, borderRadius: 14, color: "#fecaca", background: "rgba(127,29,29,.20)", border: "1px solid rgba(248,113,113,.32)", fontWeight: 850, fontSize: 12 }}>一票否決：{audit.majorFails.join("；")}</div> : null}<div style={{ marginTop: 12, display: "grid", gap: 6, color: "#cbd5e1", fontSize: 12, fontWeight: 850 }}><div>DCA：{audit.permissions?.fixedDca}</div><div>逢低：{audit.permissions?.buyTheDip}</div><div>半自動：{audit.permissions?.semiAutoDraft}</div><div>白名單候選：{audit.permissions?.whitelistCandidate ? "是" : "否"}</div><div>既有部位：{audit.permissions?.existingPosition}</div></div><CheckList title="客觀 / 特殊檢查" items={audit.financial || audit.checks || []} /><CheckList title="質化理由" items={audit.qualitative || []} /><div style={{ marginTop: 12, color: "#64748b", fontSize: 11, fontWeight: 800 }}>稽核日：{audit.auditDate}｜下次複查：{audit.nextReview}</div></article>; }

export default function V17Quality() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  useEffect(() => { fetch(`/api/v17/quality-audit?t=${Date.now()}`, { cache: "no-store" }).then((r) => r.json()).then(setData).catch((e) => setError(e.message)); }, []);
  const audits = data?.audits || [];
  const summary = data?.summary || {};
  const grouped = useMemo(() => ({ core: audits.filter((x) => ["Core", "ETF Core", "Cycle Core"].includes(x.role)), satellite: audits.filter((x) => x.role === "Satellite"), special: audits.filter((x) => ["Spec Watch", "Data Pending"].includes(x.role)) }), [audits]);
  return <main style={{ minHeight: "100vh", padding: 12, background: "radial-gradient(circle at 12% 0%, rgba(49,231,255,.16), transparent 28%), linear-gradient(180deg, #050b18, #020617)", color: "#f8fafc", fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif" }}><header style={{ padding: 16, borderRadius: 26, background: "linear-gradient(135deg, rgba(11,19,36,.92), rgba(5,11,24,.76))", border: "1px solid rgba(49,231,255,.26)", boxShadow: "0 0 46px rgba(49,231,255,.10)" }}><a href="/v17" style={{ color: "#bbf7d0", fontWeight: 900, textDecoration: "none", fontSize: 12 }}>← 回折價追蹤</a><h1 style={{ margin: "14px 0 6px", fontSize: 34, lineHeight: 1.05, color: "#e0fbff" }}>Quality Audit Center</h1><p style={{ margin: 0, color: "#94a3b8", fontWeight: 850, lineHeight: 1.45 }}>Quality Gate 是資金分配權限閘門；不是買點系統。Draft 資料不可直接作為自動交易白名單。</p>{data?.warning ? <div style={{ marginTop: 12, padding: 10, borderRadius: 14, color: "#fde68a", background: "rgba(120,53,15,.18)", border: "1px solid rgba(245,158,11,.26)", fontWeight: 900 }}>{data.warning}</div> : null}<div style={{ display: "grid", gridTemplateColumns: "repeat(5, minmax(0,1fr))", gap: 8, marginTop: 14 }}><Score label="總數" value={summary.total} /><Score label="通過" value={summary.PASSED} /><Score label="觀察" value={summary.WATCH} /><Score label="未檢查" value={summary.PENDING} /><Score label="Draft" value={summary.draft} /></div></header>{error ? <div style={{ marginTop: 14, color: "#fecaca" }}>{error}</div> : null>{!data ? <div style={{ marginTop: 18, color: "#7dd3fc", fontWeight: 900 }}>讀取中...</div> : <><section style={{ marginTop: 16 }}><h2 style={{ fontSize: 20, color: "#e0fbff" }}>第一批｜核心標的</h2><div style={{ display: "grid", gap: 12 }}>{grouped.core.map((a) => <AuditCard key={a.symbol} audit={a} />)}</div></section><section style={{ marginTop: 16 }}><h2 style={{ fontSize: 20, color: "#e0fbff" }}>第二批｜衛星標的</h2><div style={{ display: "grid", gap: 12 }}>{grouped.satellite.map((a) => <AuditCard key={a.symbol} audit={a} />)}</div></section><section style={{ marginTop: 16 }}><h2 style={{ fontSize: 20, color: "#e0fbff" }}>第三批｜特殊 / 高風險標的</h2><div style={{ display: "grid", gap: 12 }}>{grouped.special.map((a) => <AuditCard key={a.symbol} audit={a} />)}</div></section></>}</main>;
}
