#!/usr/bin/env python3
"""
Leveraged Hunter Trade Simulation

Purpose:
- Convert Leveraged Hunter tactical events into a simple trade simulation.
- This is research only. It does not execute trades.

Input:
- reports/backtests/leveraged_hunter_events.csv generated by scripts/backtest_leveraged_hunter.py

Example:
  python scripts/simulate_leveraged_hunter.py \
    --events reports/backtests/leveraged_hunter_events.csv \
    --output reports/backtests/leveraged_hunter_simulation.csv

Notes:
- First version uses event forward returns as proxy exits.
- It does not yet use real token spread / liquidity / premium-discount.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Optional, Sequence

try:
    import pandas as pd
except ImportError as exc:  # pragma: no cover
    raise SystemExit("pandas is required. Install with: pip install pandas") from exc


@dataclass
class PositionState:
    invested: float = 0.0
    open_trades: int = 0


@dataclass
class PortfolioState:
    cash_limit: float
    single_limit: float
    trade_size: float
    total_invested: float = 0.0
    realized_pnl: float = 0.0
    positions: Dict[str, PositionState] = field(default_factory=dict)
    skipped_budget: int = 0
    skipped_limit: int = 0
    trades: int = 0
    wins: int = 0
    losses: int = 0

    def can_trade(self, ticker: str) -> tuple[bool, str]:
        pos = self.positions.setdefault(ticker, PositionState())
        if self.total_invested + self.trade_size > self.cash_limit:
            return False, "總資金上限"
        if pos.invested + self.trade_size > self.single_limit:
            return False, "單檔上限"
        return True, "OK"

    def record_trade(self, ticker: str, pnl: float) -> None:
        pos = self.positions.setdefault(ticker, PositionState())
        pos.invested += self.trade_size
        pos.open_trades += 1
        self.total_invested += self.trade_size
        self.realized_pnl += pnl
        self.trades += 1
        if pnl > 0:
            self.wins += 1
        elif pnl < 0:
            self.losses += 1


def parse_pct(value) -> float:
    if pd.isna(value):
        return 0.0
    if isinstance(value, str):
        v = value.strip()
        if not v:
            return 0.0
        if v.endswith("%"):
            return float(v[:-1]) / 100.0
        return float(v)
    return float(value)


def choose_exit_return(row: pd.Series, take_profit: float, stop_loss: float, hold_col: str) -> tuple[float, str]:
    adverse = parse_pct(row.get("max_adverse_60d", 0))
    fwd = parse_pct(row.get(hold_col, 0))
    if adverse <= -abs(stop_loss):
        return -abs(stop_loss), "停損"
    if fwd >= take_profit:
        return take_profit, "停利"
    return fwd, "時間出場"


def run(args: argparse.Namespace) -> None:
    events_path = Path(args.events)
    if not events_path.exists():
        raise SystemExit(f"Missing events file: {events_path}")
    df = pd.read_csv(events_path)
    if df.empty:
        raise SystemExit("Events file is empty")
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date")

    state = PortfolioState(cash_limit=args.total_capital, single_limit=args.single_limit, trade_size=args.trade_size)
    rows = []
    hold_col = f"ret_{args.hold_days}d"
    if hold_col not in df.columns:
        raise SystemExit(f"Missing column {hold_col}; available columns: {', '.join(df.columns)}")

    for _, row in df.iterrows():
        ticker = str(row["ticker"])
        ok, reason = state.can_trade(ticker)
        if not ok:
            if reason == "總資金上限":
                state.skipped_budget += 1
            else:
                state.skipped_limit += 1
            rows.append({
                "date": row["date"],
                "ticker": ticker,
                "signal": row.get("signal", ""),
                "action": "SKIP",
                "reason": reason,
                "trade_size": 0,
                "exit_return": 0,
                "pnl": 0,
                "realized_pnl": state.realized_pnl,
                "total_invested": state.total_invested,
            })
            continue

        exit_return, exit_reason = choose_exit_return(row, args.take_profit, args.stop_loss, hold_col)
        pnl = args.trade_size * exit_return
        state.record_trade(ticker, pnl)
        rows.append({
            "date": row["date"],
            "ticker": ticker,
            "signal": row.get("signal", ""),
            "action": "TRADE",
            "reason": exit_reason,
            "trade_size": args.trade_size,
            "exit_return": exit_return,
            "pnl": pnl,
            "realized_pnl": state.realized_pnl,
            "total_invested": state.total_invested,
        })

    out = pd.DataFrame(rows)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output, index=False)

    summary = pd.DataFrame([{
        "total_capital": args.total_capital,
        "trade_size": args.trade_size,
        "single_limit": args.single_limit,
        "hold_days": args.hold_days,
        "take_profit": args.take_profit,
        "stop_loss": args.stop_loss,
        "trades": state.trades,
        "wins": state.wins,
        "losses": state.losses,
        "win_rate": state.wins / state.trades if state.trades else 0,
        "total_invested": state.total_invested,
        "realized_pnl": state.realized_pnl,
        "return_on_used_capital": state.realized_pnl / state.total_invested if state.total_invested else 0,
        "skipped_budget": state.skipped_budget,
        "skipped_limit": state.skipped_limit,
    }])
    summary_path = output.with_name(output.stem + "_summary.csv")
    summary.to_csv(summary_path, index=False)

    print(f"Simulation complete. Trades: {state.trades}, PnL: {state.realized_pnl:.2f}U")
    print(f"Wrote: {output}")
    print(f"Wrote: {summary_path}")


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Leveraged Hunter trade simulation")
    parser.add_argument("--events", default="reports/backtests/leveraged_hunter_events.csv")
    parser.add_argument("--output", default="reports/backtests/leveraged_hunter_simulation.csv")
    parser.add_argument("--total-capital", type=float, default=50.0)
    parser.add_argument("--trade-size", type=float, default=5.0)
    parser.add_argument("--single-limit", type=float, default=15.0)
    parser.add_argument("--hold-days", type=int, choices=(5, 10, 20, 60), default=20)
    parser.add_argument("--take-profit", type=float, default=0.12)
    parser.add_argument("--stop-loss", type=float, default=0.08)
    return parser.parse_args(argv)


if __name__ == "__main__":
    run(parse_args())
