#!/usr/bin/env python3
"""
Discount Hunter Trade Simulation

Purpose:
- Convert Discount Hunter layer events into a simple accumulation simulation.
- Research only. No live trading.

Input:
- reports/backtests/discount_hunter_events.csv generated by scripts/backtest_discount_hunter.py

Example:
  python scripts/simulate_discount_hunter.py \
    --events reports/backtests/discount_hunter_events.csv \
    --output reports/backtests/discount_hunter_simulation.csv
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Optional, Sequence, Set, Tuple

try:
    import pandas as pd
except ImportError as exc:  # pragma: no cover
    raise SystemExit("pandas is required. Install with: pip install pandas") from exc


@dataclass
class AssetPosition:
    invested: float = 0.0
    layers_done: Set[str] = field(default_factory=set)


@dataclass
class SimState:
    total_capital: float
    monthly_budget: float
    trade_size: float
    single_limit: float
    total_invested: float = 0.0
    positions: Dict[str, AssetPosition] = field(default_factory=dict)
    monthly_spend: Dict[str, float] = field(default_factory=dict)
    trades: int = 0
    skipped_budget: int = 0
    skipped_limit: int = 0
    skipped_duplicate_layer: int = 0

    def month_key(self, date: pd.Timestamp) -> str:
        return date.strftime("%Y-%m")

    def can_buy(self, ticker: str, layer: str, date: pd.Timestamp) -> Tuple[bool, str]:
        pos = self.positions.setdefault(ticker, AssetPosition())
        month = self.month_key(date)
        if layer in pos.layers_done:
            return False, "本層已買過"
        if self.total_invested + self.trade_size > self.total_capital:
            return False, "總資金上限"
        if pos.invested + self.trade_size > self.single_limit:
            return False, "單檔上限"
        if self.monthly_spend.get(month, 0.0) + self.trade_size > self.monthly_budget:
            return False, "月預算上限"
        return True, "OK"

    def buy(self, ticker: str, layer: str, date: pd.Timestamp) -> None:
        pos = self.positions.setdefault(ticker, AssetPosition())
        month = self.month_key(date)
        pos.invested += self.trade_size
        pos.layers_done.add(layer)
        self.total_invested += self.trade_size
        self.monthly_spend[month] = self.monthly_spend.get(month, 0.0) + self.trade_size
        self.trades += 1


def parse_pct(value) -> float:
    if pd.isna(value):
        return 0.0
    if isinstance(value, str):
        v = value.strip()
        if not v:
            return 0.0
        if v.endswith("%"):
            return float(v[:-1]) / 100.0
        return float(v)
    return float(value)


def run(args: argparse.Namespace) -> None:
    events_path = Path(args.events)
    if not events_path.exists():
        raise SystemExit(f"Missing events file: {events_path}")
    df = pd.read_csv(events_path)
    if df.empty:
        raise SystemExit("Events file is empty")
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date")

    state = SimState(
        total_capital=args.total_capital,
        monthly_budget=args.monthly_budget,
        trade_size=args.trade_size,
        single_limit=args.single_limit,
    )
    rows = []
    forward_col = f"ret_{args.eval_days}d"
    if forward_col not in df.columns:
        raise SystemExit(f"Missing {forward_col}; run discount backtest with required forward window")

    for _, row in df.iterrows():
        ticker = str(row["ticker"])
        layer = str(row.get("layer", "L?"))
        date = row["date"]
        ok, reason = state.can_buy(ticker, layer, date)
        if ok:
            state.buy(ticker, layer, date)
            eval_return = parse_pct(row.get(forward_col, 0.0))
            eval_value = args.trade_size * (1.0 + eval_return)
            action = "BUY"
        else:
            eval_return = 0.0
            eval_value = 0.0
            action = "SKIP"
            if reason in {"月預算上限", "總資金上限"}:
                state.skipped_budget += 1
            elif reason == "單檔上限":
                state.skipped_limit += 1
            elif reason == "本層已買過":
                state.skipped_duplicate_layer += 1

        rows.append({
            "date": date,
            "ticker": ticker,
            "scheme": row.get("scheme", ""),
            "layer": layer,
            "threshold": row.get("threshold", ""),
            "action": action,
            "reason": reason,
            "trade_size": args.trade_size if action == "BUY" else 0,
            "eval_return": eval_return,
            "eval_value": eval_value,
            "total_invested": state.total_invested,
            "month_spend": state.monthly_spend.get(state.month_key(date), 0.0),
        })

    out = pd.DataFrame(rows)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output, index=False)

    bought = out[out["action"] == "BUY"]
    eval_total = float(bought["eval_value"].sum()) if not bought.empty else 0.0
    summary = pd.DataFrame([{
        "total_capital": args.total_capital,
        "monthly_budget": args.monthly_budget,
        "trade_size": args.trade_size,
        "single_limit": args.single_limit,
        "eval_days": args.eval_days,
        "trades": state.trades,
        "total_invested": state.total_invested,
        "eval_total_value": eval_total,
        "eval_unrealized_pnl_proxy": eval_total - state.total_invested,
        "eval_return_proxy": (eval_total - state.total_invested) / state.total_invested if state.total_invested else 0,
        "skipped_budget": state.skipped_budget,
        "skipped_limit": state.skipped_limit,
        "skipped_duplicate_layer": state.skipped_duplicate_layer,
    }])
    summary_path = output.with_name(output.stem + "_summary.csv")
    summary.to_csv(summary_path, index=False)

    print(f"Discount Hunter simulation complete. Trades: {state.trades}, Invested: {state.total_invested:.2f}U")
    print(f"Wrote: {output}")
    print(f"Wrote: {summary_path}")


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Discount Hunter accumulation simulation")
    parser.add_argument("--events", default="reports/backtests/discount_hunter_events.csv")
    parser.add_argument("--output", default="reports/backtests/discount_hunter_simulation.csv")
    parser.add_argument("--total-capital", type=float, default=300.0)
    parser.add_argument("--monthly-budget", type=float, default=100.0)
    parser.add_argument("--trade-size", type=float, default=5.0)
    parser.add_argument("--single-limit", type=float, default=30.0)
    parser.add_argument("--eval-days", type=int, choices=(21, 63, 126, 252), default=252)
    return parser.parse_args(argv)


if __name__ == "__main__":
    run(parse_args())
