create table if not exists public.candidate_validation_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null,
  captured_at timestamptz not null default now(),
  price numeric not null check (price >= 0),
  high_52w numeric,
  low_52w numeric,
  discount_pct numeric,
  provider text,
  token_symbol text,
  shares_multiplier numeric,
  signal_level integer not null default 0,
  validation_status text not null default 'OBSERVED',
  anomaly_flags jsonb not null default '[]'::jsonb,
  triggered_by text not null check (triggered_by in ('manual','scheduled','github_actions')),
  created_at timestamptz not null default now()
);

create index if not exists candidate_validation_snapshots_symbol_captured_at_idx
  on public.candidate_validation_snapshots (symbol, captured_at desc);

create index if not exists candidate_validation_snapshots_triggered_by_idx
  on public.candidate_validation_snapshots (triggered_by, captured_at desc);

alter table public.candidate_validation_snapshots enable row level security;

comment on table public.candidate_validation_snapshots is
  'Persistent Stage 2 candidate validation snapshots. No paper positions or real trades.';

comment on column public.candidate_validation_snapshots.triggered_by is
  'Origin of snapshot: manual, scheduled, or github_actions.';
